[package]
name = "emrs-service"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
emby-proto.workspace = true
emrs-core.workspace = true
emrs-infra.workspace = true
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
thiserror.workspace = true
serde_json.workspace = true
dashmap.workspace = true
uuid.workspace = true
chrono.workspace = true
regex.workspace = true
quick-xml.workspace = true

[dev-dependencies]
tempfile = "3"
serde_json.workspace = true
sqlx.workspace = true
