[package]
name = "emrs-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "emrs_server"
path = "src/lib.rs"

[[bin]]
name = "emrs-server"
path = "src/main.rs"

[dependencies]
emby-proto.workspace = true
emrs-core.workspace = true
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true
time.workspace = true
axum.workspace = true
http.workspace = true
tower.workspace = true
tower-http.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
clap.workspace = true
base64.workspace = true
uuid.workspace = true
tokio-util.workspace = true
listen_port.workspace = true
image.workspace = true

[dev-dependencies]
tower = { workspace = true, features = ["util"] }
http.workspace = true
http-body-util = "0.1"
serde_json.workspace = true
sqlx.workspace = true
tokio = { workspace = true, features = ["net"] }
